### ISSUE TITLE
Backendと通信しようとすると通信エラーのToastが出る

### ISSUE THREAD

**Issue by atomic928** [FLAT-ICT/FLAT-Android#112]
**確認したバグ**
- login, signupをしようとすると通信エラーのToastが出る

**望ましい挙動**
- 普通に通信できる

**改善案(あれば)**
- serverが生きているか確認
- 生きているならandroid側でのリクエストが正しいか確認

**Comment by atomic928** [comment]
BASE_URLでHello, World返ってくるので、サーバー自体は生きてそう

**Comment by atomic928** [comment]
Worning出てる
`Failed to save file
                                                                                                    java.io.FileNotFoundException: /storage/emulated/0/amazonmp3/.prefs.bak: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:574)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
                                                                                                    	at com.amazon.mp3.util.FileUtil.saveToFile(FileUtil.java:463)
                                                                                                    	at com.amazon.mp3.service.metrics.CampaignMetrics.storeReferrerInfoInFile(CampaignMetrics.java:418)
                                                                                                    	at com.amazon.mp3.service.metrics.CampaignMetrics.lambda$backupReferrerInformation$1(CampaignMetrics.java:400)
                                                                                                    	at com.amazon.mp3.service.metrics.-$$Lambda$CampaignMetrics$tADWRmpQAQW2aBn6xKNPKptLcjU.call(Unknown Source:4)
                                                                                                    	at rx.Completable$8.call(Completable.java:489)
                                                                                                    	at rx.Completable$8.call(Completable.java:483)
                                                                                                    	at rx.Completable.unsafeSubscribe(Completable.java:2028)
                                                                                                    	at rx.Completable$29$1.call(Completable.java:2140)
                                                                                                    	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:221)
                                                                                                    	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.Linux.open(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8529)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:560)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
                                                                                                    	at com.amazon.mp3.util.FileUtil.saveToFile(FileUtil.java:463) 
                                                                                                    	at com.amazon.mp3.service.metrics.CampaignMetrics.storeReferrerInfoInFile(CampaignMetrics.java:418) 
                                                                                                    	at com.amazon.mp3.service.metrics.CampaignMetrics.lambda$backupReferrerInformation$1(CampaignMetrics.java:400) 
                                                                                                    	at com.amazon.mp3.service.metrics.-$$Lambda$CampaignMetrics$tADWRmpQAQW2aBn6xKNPKptLcjU.call(Unknown Source:4) 
                                                                                                    	at rx.Completable$8.call(Completable.java:489) 
                                                                                                    	at rx.Completable$8.call(Completable.java:483) 
                                                                                                    	at rx.Completable.unsafeSubscribe(Completable.java:2028) 
                                                                                                    	at rx.Completable$29$1.call(Completable.java:2140) 
                                                                                                    	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:221) 
                                                                                                    	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) `

**Comment by atomic928** [comment]
Worning出てる
`java.io.IOException: unexpected end of stream on http://34.173.190.218:3000/`
`Caused by: java.io.EOFException: \n not found: limit=0 content=…`

**Comment by atomic928** [comment]
<img width="817" alt="スクリーンショット 2022-12-26 13 28 55" src="https://user-images.githubusercontent.com/64305950/209499978-32283983-32a0-49a6-9638-b2072d88e222.png">

**Comment by atomic928** [comment]
retryOnConnectionFailure(true)にしても、interceptor追加しても意味なかった

https://stackoverflow.com/questions/72008226/android-okhttp-http-failed-java-io-ioexception-unexpected-end-of-stream
